"""
LLM-Powered Explainable AI Layer
==================================
Upgrades the rule-based explain_match() into a natural-language explanation
generated by Claude via the Anthropic API.

Design principles (to avoid hallucination / keep it trustworthy):
    - The model is given ONLY the structured facts extracted from both profiles
      (skills, domain, interests, mentoring style, etc.) — never the full free-text
      bios. This forces the explanation to be grounded in verifiable overlap,
      not the model's own guesses about the profiles.
    - The model is explicitly instructed not to invent facts not present in the
      input, and to keep the explanation to 2-3 sentences.
    - Every explanation is cached (by student_id + business_id) so re-viewing the
      same match doesn't re-trigger an API call — this matters for cost control.

Model choice: claude-haiku-4-5-20251001 by default — this is a lightweight,
low-latency, low-cost task (short structured-to-prose generation), so a smaller
model is the right fit. Swap to claude-sonnet-5 in MODEL_NAME below if you want
richer, more nuanced reasoning and don't mind the extra cost/latency.
"""

import os
import json
import hashlib
from anthropic import Anthropic

MODEL_NAME = "claude-haiku-4-5-20251001"

SYSTEM_PROMPT = """You are the explainability layer of an AI mentor-matching engine.
You will be given structured facts about a student and a business/mentor profile,
plus the cosine similarity score that caused the system to surface this match.

Your job: write a warm, concise, 2-3 sentence explanation of why this match makes sense,
grounded ONLY in the facts provided. Do not invent skills, experiences, or details not
present in the input. If there is little concrete overlap, say so honestly rather than
manufacturing a connection. Do not mention "cosine similarity" or other ML jargon in the
explanation itself — write for a student reading this on a matching app, not an engineer.
"""


def _cache_key(student_facts, business_facts):
    raw = json.dumps({"s": student_facts, "b": business_facts}, sort_keys=True)
    return hashlib.sha256(raw.encode()).hexdigest()


class LLMExplainer:
    def __init__(self, api_key=None, model_name=MODEL_NAME, cache_path="llm_explanation_cache.json"):
        self.client = Anthropic(api_key=api_key or os.environ.get("ANTHROPIC_API_KEY"))
        self.model_name = model_name
        self.cache_path = cache_path
        self.cache = self._load_cache()

    def _load_cache(self):
        if os.path.exists(self.cache_path):
            with open(self.cache_path, "r") as f:
                return json.load(f)
        return {}

    def _save_cache(self):
        with open(self.cache_path, "w") as f:
            json.dump(self.cache, f, indent=2)

    def explain(self, student_facts: dict, business_facts: dict, score: float) -> str:
        key = _cache_key(student_facts, business_facts)
        if key in self.cache:
            return self.cache[key]

        user_content = (
            f"STUDENT PROFILE FACTS:\n{json.dumps(student_facts, indent=2)}\n\n"
            f"BUSINESS/MENTOR PROFILE FACTS:\n{json.dumps(business_facts, indent=2)}\n\n"
            f"Similarity score (0-1 scale, higher = more similar): {score:.3f}\n\n"
            "Write the 2-3 sentence explanation now."
        )

        response = self.client.messages.create(
            model=self.model_name,
            max_tokens=200,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_content}],
        )

        explanation = "".join(
            block.text for block in response.content if block.type == "text"
        ).strip()

        self.cache[key] = explanation
        self._save_cache()
        return explanation


def build_student_facts(student_row):
    return {
        "major": student_row["major"],
        "domain": student_row["domain_category"],
        "skills": student_row["skills"],
        "interests": student_row["interests"],
        "target_role": student_row["target_role"],
        "preferred_mentorship_type": student_row["preferred_mentorship_type"],
    }


def build_business_facts(business_row):
    return {
        "title": business_row["title"],
        "domain": business_row["domain_category"],
        "expertise_areas": business_row["expertise_areas"],
        "mentoring_style": business_row["mentoring_style"],
        "offerings": business_row["offerings"],
        "years_experience": int(business_row["years_experience"]),
    }


if __name__ == "__main__":
    # quick manual test — requires ANTHROPIC_API_KEY set in environment
    import pandas as pd
    students = pd.read_csv("students.csv")
    businesses = pd.read_csv("businesses.csv")

    explainer = LLMExplainer()
    s = students.iloc[0]
    b = businesses.iloc[0]
    result = explainer.explain(build_student_facts(s), build_business_facts(b), score=0.42)
    print(result)
